<?php

// $passportProject = 'http://'. config('app.url');
// $zsfucaiProject = 'https://cp.' . config('app.zsfucai_url');
// $shanhujiaCpUrl = 'https://cp.' . config('app.shanhujia_url');
$passportProject = 'passport;';
$zsfucaiProject = 'zsfucai;';
$shanhujiaProject = 'shanhujia;';

return [
    'cp_menu' => [
        '权限' => [
            'logo' => 'locked',
            'menu_list' => [
                $passportProject . '/cp/user/add'                        => '新增\关闭账户',
                $passportProject . '/cp/department'                      => '组织架构',
                $passportProject . '/cp/department/actiongrouplist'   => '权限组管理',
                $passportProject . '/cp/department/resourcegrouplist' => '资源组管理',
                $passportProject . '/cp/user/addDepartmentUser'          => '新增管理员',
                $zsfucaiProject . '/log/index'                       => '操作日志',
                $passportProject . '/cp/oauth/clients'          => 'oauth客户端列表',
            ],
        ],
        '电销' => [
            'logo' => 'social-whatsapp',
            'menu_list' => [
                $zsfucaiProject. "/sellerProcess/sellerPanels" => '销售工作面板',
                $zsfucaiProject. "/sellerProcess/sellerPanelsTotal" => '销售任务管理面板',
                $zsfucaiProject. "/report/seller/process/all" => '销售目标完成度管理看板-总表',
                $zsfucaiProject. "/report/seller/process/days" => '销售目标完成度管理看板-按天',
                $zsfucaiProject. "/report/seller/process/groups" => '销售目标完成度管理看板-分拆总表',
                $zsfucaiProject. "/report/seller/process/partDays" => '销售目标完成度管理看板-分拆按天',
                $zsfucaiProject. "/sales/dailyWork" => '今日智能推荐客户',
                $zsfucaiProject. "/sales/adduser" => '添加新客户',
                $zsfucaiProject. "/sales/userlist" => '客户列表',
                $zsfucaiProject. "/user/address" => '工地列表',
                $zsfucaiProject. "/user/polt"    => '小区列表',
                $zsfucaiProject. "/sales/dataallocation" => '数据分配',
                $zsfucaiProject. "/sales/getPubseaList" => '公共海域',
                $zsfucaiProject. "/sales/findAllocation" => '查找重分配',
                $zsfucaiProject. "/sales/coupon/create" => '创建加急券',
                $zsfucaiProject. "/sales/wholesale/opfList" => '批发商户',
                $zsfucaiProject. "/sales/wholesale/saleOpfGoodsList" =>'批发价格查询',
                $zsfucaiProject. "/sales/marketing/create" => '营销工具'
            ],
        ],
        '订单' => [
            'logo' => 'bag',
            'menu_list' => [
                $zsfucaiProject. "/orders/orderList" => '订单列表',
                $zsfucaiProject. "/order/refunds" => '退换货列表',
                $zsfucaiProject. "/orders/create" => '创建订单',
                $zsfucaiProject. "/order/bonus" => '红包列表',
                $zsfucaiProject. "/order/bonusFilter" => '红包过滤器列表',
                $zsfucaiProject. "/zone/list" => '优惠专区列表',
            ],
        ],
        '物流' => [
            'logo' => 'android-bus',
            'menu_list' => [
                $zsfucaiProject. "/express/dispatchPanel" => '调度工作面板',
                $zsfucaiProject. "/expresses" => '物流排线列表',
                $zsfucaiProject. "/salestats/shippingPanel" => '物流运力面板',
                $zsfucaiProject. "/express/carLocation" => '车辆实时位置面板',
                $zsfucaiProject. "/express/drivers/signin" => '签到司机列表',
                $zsfucaiProject. "/express/driverBill" => '物流司机结算',
                $zsfucaiProject. "/express/porterBill" => '物流搬运工结算',
                $zsfucaiProject. "/express/driverBillTotal" => '司机结算汇总',
                $zsfucaiProject. "/express/porterBillTotal" => '搬运工结算汇总',
                $zsfucaiProject. "/express/drivers" => '司机列表',
                $zsfucaiProject. "/express/porters" => '搬运工列表',
                $zsfucaiProject. "/report/express/driverToolReport" => '司机小程序使用明细',
                $zsfucaiProject. "/report/express/driverToolTotal" => '司机小程序使用汇总',
                $zsfucaiProject. "/express/dispatch/feeCalc" => '物流费用计算器',
                $zsfucaiProject. "/express/obdManage" => 'OBD盒子管理页面',
                $zsfucaiProject. "/express/truckOperation" => '车辆运营报表',
                $zsfucaiProject. "/express/repertoryBoard" => '仓库场内操作看板',
            ],
        ],  
         '采购' => [
            'logo' => 'document-text',
            'menu_list' => [
                // "/purchasestore/create" => '新增采购单',
                $zsfucaiProject . "/purchasestore/list" => '采购单列表',
                // "/purchaserefund/create" => '新增采购退货单',
                $zsfucaiProject . "/purchaserefund/list" => '采购退货单列表',
                $zsfucaiProject . "/report/unsalableGoods" => '滞销报表',
                $zsfucaiProject . "/purchase/temp" => '临采明细',
                $zsfucaiProject . "/purchase/bill" => '临采账务',
                $zsfucaiProject . "/goods/stockWarning" => '库存预警',
                // "/purchase/profit/skuProfit" => '商品毛利',
                // "/purchase/profit/skuProfitnew" => '商品毛利(新，测试)',
                $zsfucaiProject . "/purchase/order/index" => '临采订单占比',
                // "/purchase/profit/catProfit" => '毛利汇总',
                $zsfucaiProject . "/report/oemKeyData" => 'OEM-壁贝关键数据报表',
                $zsfucaiProject . "/report/OEMReport" => 'OEM销售数据报表',
                $zsfucaiProject . "/report/newWoodsReport" => '新木类数据报表',
                $zsfucaiProject . "/purchase/profit/classProfit" => '分类毛利报表',
                $zsfucaiProject . "/report/goodsSale/categoryInfo" => '品类销售数据',
                $zsfucaiProject . "/report/goodsSale/brandInfo" => 'TOP10品牌销售数据',
                $zsfucaiProject . "/report/goodsSale/skuInfo" => 'TOP20商品销售数据',
                $zsfucaiProject . "/report/goodsSale/salerInfo" => '商品销售概况',
                $zsfucaiProject . "/goods/exammingReport" => '商品检测报告',
                $zsfucaiProject . "/report/powderOemReplaceRate" => '粉类OEM替代率数据报表',
                $zsfucaiProject . "/report/powderOemCustomerReplaceRate" => '粉类-客户OEM替代率报表',
                // "/purchase/purchaseList" => '采购单',
                $zsfucaiProject . "/purchase/profit/skuProfitnewTest" => '商品毛利(最新)',
            ],
        ],    
         '工单' => [
            'logo' => 'network',
            'menu_list' => [
                $zsfucaiProject . "/workorders" => '工单列表',
                $zsfucaiProject . "/workorders/create" => '创建工单',
                $zsfucaiProject . "/append/orderAppend" => '增补单列表',
            ],
        ], 
        '报表' => [
            'logo' => 'stats-bars',
            'menu_list' => [
                'G2' => [
                    $zsfucaiProject. "/report/okr/index" => 'G2看板',
                    $zsfucaiProject. "/report/seller/sellerAchievement" => '销售业绩总报表',
                ],
                '通用' => [
                    $zsfucaiProject . '/exportData/order/orderDeliveryInfo' => '自助导出数据',
                    $zsfucaiProject . "/salestats/rePurchaseRate" => '复购率报表',
                    $zsfucaiProject . "/salestats/orderTime" => '订单节点效率图',
                    $zsfucaiProject . '/report/skuDimensionPriceCost' => 'sku维度的价格和成本数据',
                    $zsfucaiProject . '/report/homeDecorateBoom' => '家装景气指数',
                    $zsfucaiProject . '/report/compDecorateBoom' => '工装景气指数',
                ],
                '销售' => [
                    $zsfucaiProject . "/report/salerPerformance" => '销售绩效统计报表',
                    $zsfucaiProject . "/report/salerPerformance/hr"=> '销售绩效统计表（原始版）',
                    $zsfucaiProject . "/sales/firstOrderReferReport" => '首单渠道数据报表',
                    $zsfucaiProject . "/report/incomeCostReport" => '成本收入关键数据报表',
                    $zsfucaiProject . "/reportform/salerank" => '销售排行榜',
                    $zsfucaiProject . "/report/seller/online/pk" => '销售线上下单争霸赛报表',
                    $zsfucaiProject . "/reportform/dailySaleRank" => '掌辅英雄榜',
                    $zsfucaiProject . "/reportform/sellingPK" => '销售PK赛况表',
                    $zsfucaiProject . "/salestats/sellerDailyReport" => '销售每日关键数据',
                    $zsfucaiProject . "/salestats/smartPanel" => '智能推荐面板跟进报表',
                    $zsfucaiProject . '/report/seller/address' => '工地管理报表',
                    $zsfucaiProject . "/report/orderPriceStat" => '客单价区间报表',
                    $zsfucaiProject . "/report/OrderPriceReport" => '客单价趋势报表',
                    $zsfucaiProject . "/report/SABGoodsReport" => 'SAB商品的报表',
                    $zsfucaiProject . "/salestats/compCustomer" => '企业客户对账表',
                    $zsfucaiProject . "/reportform/saleReport" => '销售管理报表',
                    $zsfucaiProject . "/salestats/keyCustomer" => '重点客户数据',
                    $zsfucaiProject . "/salestats/keyCustomerTrend" => '重点客户数据趋势图',
                    $zsfucaiProject . "/report/CustomerRecommentReport" => '客户评价数据',
                    $zsfucaiProject . '/report/marketCost' => '市场成本明细报表',
                    $zsfucaiProject . '/report/sellerImportCustom' => '销售录入数据报表'
                    // "/salestats/smartPanelEffects" => '智能推荐面板效果报表',
                ],
                '销售-风控'=>[
                    $zsfucaiProject . "/sales/unpayOrderList" => '欠款订单列表',
                    $zsfucaiProject . "/sales/unpayUser" => '应收-客户列表',
                    $zsfucaiProject . "/salestats/badOrderAmount" => '不良应收管理报表',
                    $zsfucaiProject . "/reportform/salerReceiving" => '应收列表',
                    $zsfucaiProject . "/report/chargeIncrement" => '总监主管绩效统计报表',
                    $zsfucaiProject . "/report/salerBadAmount" => '销售坏账扣款报表',
                ],
                '客服售后' => [
                    $zsfucaiProject . '/report/servicePerformanceReport' => '客服绩效统计报表',
                    $zsfucaiProject . "/salestats/refundTime" => '退换货节点效率图',
                    $zsfucaiProject . "/report/subsidyDetail" => '售后补贴明细表',
                ],
                '物流' => [
                    $zsfucaiProject . "/reportform/shipping" => '物流费用汇总表',
                    $zsfucaiProject . "/reportform/shippingDetail" => '物流费用明细表',
                    $zsfucaiProject . '/report/driverManage' => '核心司机运营报表',
                    $zsfucaiProject . '/report/driver/driverRank' => '掌辅司机英雄榜',
                    $zsfucaiProject . "/salestats/lateMatch" => 'OBD和司机小程序迟配报表',
                    $zsfucaiProject . "/report/storageExpressReport" => '自营联营仓储物流报表',
                    $zsfucaiProject . "/report/express/ExpressLoadTime" => '物流装车时效报表',
                    $zsfucaiProject . "/report/express/ExpressUseTime" => '配送单各流程耗时表',
                    $zsfucaiProject . "/report/warehouse" => '库房绩效统计报表',
                ],
                '采购' => [
                    $zsfucaiProject . '/report/purchaseTemporaries' => '临采时效报表',
                    $zsfucaiProject . "/report/purchasePriChangeReport" => '采购价格变更记录',
                    $zsfucaiProject . "/report/oversales/list" => '超卖商品报表',
                ],
                '缺货统计' => [
                    $zsfucaiProject . '/report/stockout' => '缺货统计',
                    $zsfucaiProject . '/report/orderStockout' => '缺货统计（下单后）'
                ],
                '联营' => [
                    $zsfucaiProject . '/report/sandOrder' => '砂石销售概况',
                    $zsfucaiProject . '/report/sandProfit/detail' => '砂石毛利报表',
                ],
            ],
        ], 
        '商品及供应商' => [
            'logo' => 'stats-bars',
            'menu_list' => [
                // "/goods/purchase" => '商品采购信息',
                $zsfucaiProject . "/goods/addGoods" => '商品添加',
                $zsfucaiProject . "/goods/goodsList" => '商品列表',
                $zsfucaiProject . "/supplier/addSupplier" => '供应商添加',
                $zsfucaiProject . "/supplier/supplierList" => '供应商列表',
                $zsfucaiProject . "/goods/showLargeOrder" => '商品价格',
            ],
        ],
        '联营' => [
            'logo' => 'document-text',
            'menu_list' => [
                $zsfucaiProject . "/thirdParty/transportation" => '联营商运力管理面板',
                $zsfucaiProject . "/purchase/thirdSupplierBill/billList" => '联营订单费用表',
                $zsfucaiProject . "/goods/thirdParty" => '联营商品列表',
                $zsfucaiProject . "/thirdParty/manageThirdParty" => '联营商列表',
            ],
        ], 
        '财务' => [
            'logo' => 'social-yen',
            'menu_list' => [
                $zsfucaiProject . "/finance/transfer" => '转账工具',
                $zsfucaiProject . "/finance/subsidy" => '补贴工具',
                $zsfucaiProject . "/finance/goOnline" => '付款明细',
                "应付" => [
                    $zsfucaiProject . "/charge/list" => '记账单列表',
                    $zsfucaiProject . "/payment/list" => '付款单列表',
                    $zsfucaiProject . "/chargeoff/list" => '核销单列表',
                ],
            ],
        ],
        'KA'  => [
            'logo' => 'person',
            'menu_list' => [
                $zsfucaiProject . "/ka/publicSea" => 'KA公海',
                $zsfucaiProject . "/ka/selfSea" => 'KA私海',
                $zsfucaiProject . "/ka/dutiesList" => '任务列表',
                $zsfucaiProject . "/ka/company/list" => 'KA签约客户表',
                $zsfucaiProject . "/ka/companyOrder" => 'KA客户对账表',
                $zsfucaiProject . "/ka/compBill" => 'KA客户对账表(汇总表)',
                $zsfucaiProject . "/ka/companyPermeation" => '企业客户渗透管理报表',
                $zsfucaiProject . "/ka/companyOperation" => 'KA核心运营指标报表',
            ],
        ],
        '仓库' => [
            'logo' => 'model-s',
            'menu_list' => [
                // "/instore/create" => '新增入库单',
                $zsfucaiProject . "/instore/list" => '入库单列表',
                // "/outstore/create" => '新增出库单',
                $zsfucaiProject . "/outstore/list" => '出库单列表',
                $zsfucaiProject . "/check/list" => '盘点单列表',
                $zsfucaiProject . "/gainloss/list" => '损益单列表',
                $zsfucaiProject . "/stock/list" => '库存查询',
                $zsfucaiProject . "/inoutquery/list" => '产品出入库查询',
            ],
        ],
        '珊瑚家' => [
            'logo' => 'ios-home',
            'menu_list' => [
                $shanhujiaProject . "/" => '珊瑚家欢迎页',
                $shanhujiaProject . "/goods" => '商品',
                $shanhujiaProject . "/order" => '订单',
            ],
        ],
    ],
];
